name: The Autumn Co
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25011
title: The Autumn Co.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeeee'
    - '#292929'
    - '#060606'
    - '#8b8b8b'
    - '#adadad'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
